services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=splearn'
      - 'MYSQL_USER=spring'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
    ports:
      - '13366:3306'